name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/fileserver:${{ github.sha }} .

    - name: Add test data
      run: mkdir -p testdata && echo "This is a test file." > testdata/testfile.txt

    - name: Test the Docker image
      run: |
        docker run -d -p 8080:8080 -v $(pwd)/testdata:/root --name fileserver ghcr.io/${{ github.repository }}/fileserver:${{ github.sha }}
        sleep 10
        curl -f http://localhost:8080/testfile.txt || (docker logs fileserver && exit 1)
        docker stop fileserver
        docker rm fileserver

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/fileserver:${{ github.sha }}

    - name: Create a new release
      uses: actions/create-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: Automated release for commit ${{ github.sha }}
        draft: false
        prerelease: false
